name: 'iOS end to end tests action'
description: 'Prepares and runs end to end tests on iOS device'
inputs:
  ios_device_pin_code:
    description: 'iOS Device Pin Code'
    required: true
  test_device_identifier_uuid:
    description: 'Test Device Identifier UUID'
    required: true
  has_time_account_number:
    description: 'Has Time Account Number'
    required: true
  no_time_account_number:
    description: 'No Time Account Number'
    required: true
  test_device_udid:
    description: 'Test Device UDID'
    required: true
  xcode_test_plan:
    description: 'Xcode Test Plan to run'
    required: true

  runs:
    using: 'composite'
    steps:
    - name: Configure Xcode project
      run: |
        for file in *.xcconfig.template ; do cp $file ${file//.template/} ; done
        sed -i "" "/MULLVAD_IOS_DEVICE_PIN_CODE =/ s/= .*/= ${{ inputs.ios_device_pin_code }}/" UITests.xcconfig
        sed -i "" "/MULLVAD_TEST_DEVICE_IDENTIFIER_UUID =/ s/= .*/= ${{ inputs.test_device_identifier_uuid }}/" UITests.xcconfig
        sed -i "" "/MULLVAD_HAS_TIME_ACCOUNT_NUMBER =/ s/= .*/= ${{ inputs.has_time_account_number }}/" UITests.xcconfig
        sed -i "" "/MULLVAD_NO_TIME_ACCOUNT_NUMBER =/ s/= .*/= ${{ inputs.no_time_account_number }}/" UITests.xcconfig
      working-directory: ios/Configurations

    - name: Run end-to-end-tests
      run: |
        set -o pipefail && env NSUnbufferedIO=YES xcodebuild \
          -project MullvadVPN.xcodeproj \
          -scheme MullvadVPNUITests \
          -testPlan {{ inputs.xcode_test_plan }} \
          -destination "platform=iOS,id=${{ inputs.test_device_udid }}" \
          test 2>&1 | xcbeautify --report junit --report-path test-report
      working-directory: ios/